---
application:
  name: "minikriateve"
  project: "mini-kriateve"
  organization: "QoveryCommunity"
routers:
- name: "main-minikriateve"
  routes:
  - application_name: "minikriateve"
    paths:
    - "/*"
